<?php
namespace app\models;

use yii\db\ActiveRecord;
use yii\web\UploadedFile;

class FileUpload extends ActiveRecord
{
    /**
     * @var UploadedFile
     */
    public $uploadFile;

    public function rules()
    {
        return [
            [['uploadFile'],
             'file',
             'skipOnEmpty' => false,
             'extensions' => 'png, jpg,jpeg',
             'mimeTypes' => 'image/x-citrix-jpeg,image/png'
            ],
        ];
    }

    public function upload()
    {
        if ($this->validate()) {

            $uploadPath =   '/uploads/'.date('Ymd') . '/';
            $this->fileExists(dirname(__DIR__).'/web'.$uploadPath);
            $uploadPath .= date('YmdHis') . rand(10000,99999) . '.' . $this->uploadFile->extension;
            $res = $this->uploadFile->saveAs(dirname(__DIR__).'/web'.$uploadPath);
//           var_dump($res,$uploadPath);exit;
           return \Yii::$app->request->getHostInfo().$uploadPath;
        } else {
            return false;
        }
    }

    public function fileExists($uploadpath)
    {
        if(!file_exists($uploadpath)){
            mkdir($uploadpath);
        }
        return $uploadpath;
    }

    /**
     * @param bool $insert
     * @return bool
     * @author wang
     */
    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}