<?php
/**
 * @package    http://www.rulaiyun.cn/
 * @author     wang <wangyaxu7019@dingtalk.com>
 * @copyright  Copyright &copy; rulaiyun.cn,2018 - 2019
 */

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "jl_children_project".
 *
 * @property int    $id
 * @property string $parent_id              对应项目id
 * @property string $name                   项目分段名称
 * @property int    $principal              项目分段负责人
 * @property int    $progress               项目进度
 * @property int    $picture_path           图片路径
 * @property string $create_time           创建时间
 * @property string $update_time           更新时间
 */
class Projectchildren extends FileUpload
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%children_project}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required',],
            [['principal','picture_path'], 'safe'],
            [['progress'], 'number','max'=>100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '项目分段名称',
            'progress' => '项目分段进度',
            'principal' => '项目分段负责人',
            'picture_path' => '图片路径',
            'create_time' => '创建日期',
            'update_time' => '更新日期',
        ];
    }


    /**
     * @param bool $insert
     * @return bool
     * @author wang
     */
    public function beforeSave($insert)
    {
        if (!empty($this->uploadFile)) {
            $this->picture_path = $this->upload();
        }
        if ($insert) {    //新增
            $this->create_time = date('Y-m-d H:i:s');
            $this->update_time = date('Y-m-d H:i:s');
        } else {    //修改
            $this->update_time = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param bool  $insert
     * @param array $changedAttributes
     * @author wang
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * 删除之后
     */
    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }


}
