<?php
/**
 * @package    http://www.rulaiyun.cn/
 * @author     wang <wangyaxu7019@dingtalk.com>
 * @copyright  Copyright &copy; rulaiyun.cn,2018 - 2019
 */

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "jl_project".
 *
 * @property int    $id
 * @property string $name                   项目名称
 * @property string $number                 项目编号
 * @property int    $category               分类
 * @property int    $province               省
 * @property int    $city                   市
 * @property int    $area                   区县
 * @property string $content                  详细信息
 * @property string $create_time           创建时间
 * @property string $update_time           更新时间
 */
class Project extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%project}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required',],
            [['number'], 'unique'],
            [['category', 'province', 'city', 'area'], 'integer'],
            [['content'], 'safe'],
            [['number'], 'number','max'=>99999999,'on'=>'create'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'number' => '项目编号',
            'name' => '项目名称',
            'content' => '项目内容',
            'category' => '项目分类',
            'province' => '省',
            'city' => '市',
            'area' => '县',
            'create_time' => '创建日期',
            'update_time' => '更新日期',
        ];
    }

    public function getChildren()
    {
        /**
         * 第一个参数为要关联的字表模型类名称，
         *第二个参数指定主表的关联字段
         */
        return $this->hasMany(Projectchildren::className(), ['parent_id' => 'id']);
    }


    /**
     * @param bool $insert
     * @return bool
     * @author wang
     */
    public function beforeSave($insert)
    {
        if ($insert) {    //新增
            $this->create_time = date('Y-m-d H:i:s');
            $this->update_time = date('Y-m-d H:i:s');
            if (empty($this->number)) {
                $sql='SELECT MAX(number) AS `max` FROM jl_project';
                $rows=\Yii::$app->db->createCommand($sql)->query()->read();
                $res = explode('_',$rows['max']);
                if (empty($res[1])) {
                    $this->number = 'jl_000001';
                } else {
                    $int = (int)$res[1] + 1;
                    $this->number = 'jl_' . str_pad($int,6,0,STR_PAD_LEFT);
                }
            } else {
                $this->number = str_pad($this->number,9,0,STR_PAD_LEFT);
            }
        } else {    //修改
            $this->update_time = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param bool  $insert
     * @param array $changedAttributes
     * @author wang
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * 删除之后
     */
    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }


}
